name: Trivy Binary and dd-import Binary

on: [workflow_dispatch]

jobs:
  dd-import_example:

    runs-on: ubuntu-latest

    env:
      DD_URL: https://demo.defectdojo.org
      DD_API_KEY: 548afd6fab3bea9794a41b31da0e9404f733e222
      DD_PRODUCT_TYPE_NAME: GitHub
      DD_PRODUCT_NAME: ${{ github.event.repository.name }}
      

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install semgrep dd-import

      - name: Install Trivy
        run: |
          sudo apt-get install wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy

      
      - name: Semgrep check
        run: |
          semgrep scan --json -o semgrep.json --config auto
      
      - name: Upload Semgrep check to DefectDojo
        env:
          DD_TEST_NAME: Semgrep
          DD_TEST_TYPE_NAME: Semgrep JSON Report
          DD_FILE_NAME: semgrep.json
          DD_SERVICE: dd-import-service
          DD_ENGAGEMENT_NAME: GitHub Actions Initated by semgrep scan
        run: |
          dd-reimport-findings

      - name: Trivy check
        run: |
          trivy fs . -o trivy.json

      - name: Upload Trivy scan to DefectDojo
        env:
          DD_TEST_NAME: Trivy
          DD_TEST_TYPE_NAME: Trivy Scan
          DD_FILE_NAME: trivy.json
          DD_SERVICE: trivy-service
          DD_ENGAGEMENT_NAME: GitHub Actions Initated by trivy scan
        run: |
          dd-reimport-findings

